# Generated by Django 4.2.9 on 2025-05-20 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_remove_stripesubscription_date_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="current_period_end",
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 14, 23, 18, 766115)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="current_period_start",
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 20, 14, 23, 41, 906468)),
            preserve_default=False,
        ),
    ]
