# Generated by Django 4.2.9 on 2025-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_stripesubscription_current_period_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
