# Generated by Django 4.2.9 on 2025-09-25 13:59

import bitapi.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0011_stripesubscription_auto_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripepayment",
            name="date_created",
            field=models.DateTimeField(db_index=True, default=bitapi.utils.now),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="date_created",
            field=models.DateTimeField(db_index=True, default=bitapi.utils.now),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
