# Generated by Django 5.2.8 on 2026-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_default_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=256, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("unpaid", "Unpaid"),
                    ("paused", "Paused"),
                ]
            ),
        ),
    ]
