# Generated by Django 5.2.8 on 2026-01-27 16:05

import core.models
from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="end_period",
            field=models.DateTimeField(default=core.models.now_plus_one_month),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("unpaid", "Unpaid")]
            ),
        ),
    ]
