# Generated by Django 5.2.8 on 2026-01-28 00:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_subscription_end_period_alter_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_period",
            field=models.DateTimeField(
                default=core.models.now_plus_one_month, null=True
            ),
        ),
    ]
