# Generated by Django 5.2.8 on 2026-01-11 16:50

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_period",
            field=models.DateTimeField(default=core.helpers.now),
        ),
    ]
