# Generated by Django 5.2.8 on 2026-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yookassa_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("canceled", "Canceled")]
            ),
        ),
    ]
