# Generated by Django 5.2.8 on 2026-01-28 00:45

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yookassa_payments", "0002_alter_paymentmethod_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="period_start",
            field=models.DateTimeField(default=core.helpers.now),
        ),
    ]
