# Generated by Django 5.2.8 on 2026-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yookassa_payments", "0003_alter_payment_period_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("pending", "Pending"),
                ]
            ),
        ),
    ]
