# Generated by Django 4.2.9 on 2025-05-20 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("date_created", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeSubscription",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("session_id", models.CharField(max_length=256, null=True)),
                ("status", models.CharField(default="init", max_length=64)),
                ("type", models.CharField(max_length=64)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("date_ended", models.DateTimeField(null=True)),
                ("data", models.JSONField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.stripecustomer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("session_id", models.CharField(max_length=256, null=True)),
                ("type", models.CharField(max_length=64)),
                ("status", models.CharField(default="init", max_length=64)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.stripecustomer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.stripesubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
