# Generated by Django 4.2.9 on 2025-05-20 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscription_payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stripesubscription",
            old_name="type",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="stripepayment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="customer",
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StripeCustomer",
        ),
    ]
