# Generated by Django 4.2.9 on 2025-05-20 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_rename_type_stripesubscription_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="session_id",
        ),
        migrations.RemoveField(
            model_name="stripesubscription",
            name="session_id",
        ),
    ]
