# Generated by Django 4.2.9 on 2025-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_remove_stripepayment_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripesubscription",
            name="date_ended",
        ),
    ]
