# Generated by Django 4.2.9 on 2025-05-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription_payments", "0006_stripesubscription_canceled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="subscription",
        ),
        migrations.AddField(
            model_name="stripesubscription",
            name="next_price",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
