# Generated by Django 4.2.9 on 2025-06-02 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription_payments", "0007_remove_stripepayment_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripesubscription",
            name="next_price",
        ),
    ]
