# Generated by Django 4.2.9 on 2025-06-02 14:10

import bitapi.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription_payments", "0008_remove_stripesubscription_next_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="stripepayment",
            name="date_created",
            field=models.DateTimeField(default=bitapi.utils.now),
        ),
        migrations.AlterField(
            model_name="stripesubscription",
            name="date_created",
            field=models.DateTimeField(default=bitapi.utils.now),
        ),
    ]
