# Generated by Django 4.2.9 on 2025-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_alter_stripesubscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesubscription",
            name="auto_pay",
            field=models.JSONField(null=True),
        ),
    ]
