# Используем официальный Python
FROM python:3.12-slim

# Создаём рабочую директорию в контейнере
WORKDIR /app



# Устанавливаем Python зависимости
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Копируем весь проект в контейнер
COPY . .

# Открываем порт для Django
EXPOSE 8000

# По умолчанию запускаем Django сервер (можно переопределить в docker-compose)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
