# Generated by Django 5.2.8 on 2025-11-28 15:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmbeddingLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("dimensions", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TextEmbeddingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "embedding_logs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="embeddings.embeddinglogs",
                    ),
                ),
            ],
        ),
    ]
