# Generated by Django 5.2.8 on 2025-11-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embeddings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="embeddinglogs",
            name="dimensions",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
