# Generated by Django 5.2.8 on 2025-11-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("embeddings", "0002_alter_embeddinglogs_dimensions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="embeddinglogs",
            options={
                "verbose_name": "Embedding Log",
                "verbose_name_plural": "Embedding Logs",
            },
        ),
    ]
