# Generated by Django 5.2.8 on 2025-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
