# Generated by Django 5.2.8 on 2025-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="may_have_trial",
            field=models.BooleanField(default=True),
        ),
    ]
