# Generated by Django 4.2.9 on 2024-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="free_limit",
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
