# Generated by Django 4.2.9 on 2024-04-14 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address_user_free_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="free_limit",
            new_name="remain_words",
        ),
    ]
