# Generated by Django 4.2.9 on 2024-04-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_free_limit_user_remain_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="granted_words",
            field=models.PositiveIntegerField(default=5000000),
        ),
        migrations.AddField(
            model_name="user",
            name="used_words",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
