# Generated by Django 4.2.9 on 2024-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_granted_words_user_used_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="granted_words",
            field=models.PositiveIntegerField(default=50000),
        ),
    ]
