# Generated by Django 4.2.9 on 2024-05-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_granted_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rps",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
