# Generated by Django 4.2.9 on 2024-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_rps"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.CharField(choices=[("Free", "Free"), ("Premium", "Premium")], default="Free"),
        ),
    ]
