# Generated by Django 4.2.9 on 2024-09-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_subscriberequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberequest",
            name="usern_name",
            field=models.CharField(default="", max_length=500),
        ),
    ]
