# Generated by Django 4.2.9 on 2024-09-10 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_subscriberequest_usern_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriberequest",
            old_name="usern_name",
            new_name="name",
        ),
    ]
