# Generated by Django 4.2.9 on 2024-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_invoicerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberequest",
            name="generate_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriberequest",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="InvoiceRequest",
        ),
    ]
