# Generated by Django 4.2.9 on 2024-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_subscriberequest_generate_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberequest",
            name="invoice_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
