# Generated by Django 4.2.9 on 2024-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_subscriberequest_invoice_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="granted_words",
            new_name="granted_words_deep_scan",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="used_words",
            new_name="used_words_deep_scan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="remain_words",
        ),
        migrations.AddField(
            model_name="user",
            name="granted_words_simple_scan",
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name="user",
            name="used_words_simple_scan",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
