# Generated by Django 4.2.9 on 2024-10-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_rename_granted_words_user_granted_words_deep_scan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_type",
            field=models.CharField(default="Email", max_length=20),
        ),
    ]
