# Generated by Django 4.2.9 on 2024-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_registration_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="granted_british_words",
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name="user",
            name="used_british_words",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
