# Generated by Django 4.2.9 on 2024-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_granted_british_words_user_used_british_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="granted_british_rps",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
