# Generated by Django 4.2.9 on 2024-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_user_granted_british_rps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="granted_british_words",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
