# Generated by Django 4.2.9 on 2024-10-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_granted_british_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_anon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="registered_user",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
