# Generated by Django 4.2.9 on 2024-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_user_is_anon_user_registered_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="words_per_generation_limit",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
