# Generated by Django 4.2.9 on 2024-11-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_words_per_generation_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriberequest",
            name="is_free",
            field=models.BooleanField(default=False),
        ),
    ]
