# Generated by Django 4.2.9 on 2024-12-16 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_subscriberequest_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_limits_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='granted_words_deep_scan',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='granted_words_simple_scan',
            field=models.PositiveIntegerField(default=30000),
        ),
    ]
