# Generated by Django 4.2.9 on 2025-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_last_limits_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Custom', 'Custom')], default='Free'),
        ),
    ]
