# Generated by Django 4.2.9 on 2025-01-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_or_custom_available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
