# Generated by Django 4.2.9 on 2025-02-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_premium_or_custom_available_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='words_per_generation_limit',
        ),
    ]
