# Generated by Django 4.2.9 on 2025-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_remove_words_per_generation_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="policy_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
