# Generated by Django 4.2.9 on 2025-02-12 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_policy_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place', models.CharField(blank=True, max_length=500)),
                ('role', models.CharField(blank=True, max_length=500)),
                ('ai_detector_purpose', models.TextField(blank=True)),
                ('current_solution', models.TextField(blank=True)),
                ('discovery_source', models.CharField(blank=True, max_length=500)),
                ('other_tools', models.TextField(blank=True)),
                ('important_features', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
