# Generated by Django 4.2.9 on 2025-02-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='role',
        ),
    ]
