# Generated by Django 4.2.9 on 2025-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_questionnaire_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
