# Generated by Django 4.2.9 on 2025-02-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_enrolled_user_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscriberequest',
            name='name',
        ),
    ]
