# Generated by Django 4.2.9 on 2025-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="client_id",
            field=models.CharField(null=True),
        ),
    ]
