# Generated by Django 4.2.9 on 2025-03-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_client_id'),
        ('users', '0032_user_subscription_start_date'),
    ]

    operations = [
    ]
