# Generated by Django 4.2.9 on 2025-03-05 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_merge_20250301_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_upload_file', models.BooleanField(default=False)),
                ('history_retention', models.BooleanField(default=False)),
                ('history_retention_period_days', models.PositiveIntegerField(default=30)),
                ('can_view_stats', models.BooleanField(default=False)),
                ('can_generate_report', models.BooleanField(default=False)),
                ('subscription', models.CharField(choices=[('Free', 'Free'), ('Pay as you go', 'Pay as you go'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Free')),
                ('rps', models.PositiveIntegerField(default=1)),
                ('granted_british_rps', models.PositiveIntegerField(default=1000)),
                ('granted_words_deep_scan', models.PositiveIntegerField(default=10000)),
                ('granted_words_simple_scan', models.PositiveIntegerField(default=30000)),
                ('granted_british_words', models.PositiveIntegerField(default=1000)),
                ('deep_scan_mode', models.BooleanField(default=False)),
                ('gpt_plugin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
