# Generated by Django 4.2.9 on 2025-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_userpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_generate_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_upload_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deep_scan_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gpt_plugin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='history_retention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='history_retention_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Pay as you go', 'Pay as you go'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Free'),
        ),
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
