# Generated by Django 4.2.9 on 2025-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_can_generate_report_user_can_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_generate_report',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_upload_file',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_view_stats',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deep_scan_mode',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gpt_plugin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='history_retention',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='history_retention_period_days',
            field=models.PositiveIntegerField(default=30, null=True),
        ),
    ]
