# Generated by Django 4.2.9 on 2025-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_can_generate_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_api_key',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
