# Generated by Django 4.2.9 on 2025-03-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_socialmediasubscriberequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='job_position',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='job_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='work_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
