# Generated by Django 4.2.9 on 2025-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_questionnaire_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ip",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
