# Generated by Django 4.2.9 on 2025-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_user_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privy_id",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
