# Generated by Django 4.2.9 on 2025-04-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_can_create_plagiarism_request'),
        ('users', '0040_user_privy_id'),
    ]

    operations = [
    ]
