# Generated by Django 4.2.9 on 2025-04-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0041_merge_20250410_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registered_user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
