# Generated by Django 4.2.9 on 2025-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_merge_20250410_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberequest',
            name='role_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
