# Generated by Django 4.2.9 on 2025-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_subscriberequest_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_plagiarism_attempts',
            field=models.PositiveIntegerField(default=10, null=True),
        ),
    ]
