# Generated by Django 4.2.9 on 2025-05-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_registered_user'),
        ('users', '0043_user_free_plagiarism_attempts'),
    ]

    operations = [
    ]
