# Generated by Django 4.2.9 on 2025-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_merge_20250502_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch_doc_upload',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_upload_limit_mb',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Pay as you go', 'Pay as you go'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise'), ('Pro', 'Pro')], default='Free'),
        ),
    ]
