# Generated by Django 4.2.9 on 2025-05-20 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0046_user_customer_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="batch_doc_upload",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_create_api_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_create_plagiarism_request",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_generate_report",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_upload_file",
        ),
        migrations.RemoveField(
            model_name="user",
            name="can_view_stats",
        ),
        migrations.RemoveField(
            model_name="user",
            name="document_upload_limit_mb",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gpt_plugin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="granted_british_rps",
        ),
        migrations.RemoveField(
            model_name="user",
            name="granted_british_words",
        ),
        migrations.RemoveField(
            model_name="user",
            name="granted_words_deep_scan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="granted_words_simple_scan",
        ),
        migrations.RemoveField(
            model_name="user",
            name="history_retention",
        ),
        migrations.RemoveField(
            model_name="user",
            name="history_retention_period_days",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rps",
        ),
    ]
