# Generated by Django 4.2.9 on 2025-05-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0047_remove_user_batch_doc_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="additional_limits",
            field=models.JSONField(default=dict),
        ),
    ]
