# Generated by Django 4.2.9 on 2025-06-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0048_user_additional_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unsubscribed_emails",
            field=models.BooleanField(default=False),
        ),
    ]
