# Generated by Django 4.2.9 on 2025-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0049_user_unsubscribed_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="grant_credits_cents",
            field=models.IntegerField(default=0),
        ),
    ]
