# Generated by Django 4.2.9 on 2025-06-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0050_user_grant_credits_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="popup",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
