# Generated by Django 4.2.9 on 2025-06-25 15:31

import bitapi.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0051_user_popup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriberequest",
            name="generate_invoice",
        ),
        migrations.RemoveField(
            model_name="subscriberequest",
            name="invoice_id",
        ),
        migrations.RemoveField(
            model_name="subscriberequest",
            name="invoice_url",
        ),
        migrations.AddField(
            model_name="subscriberequest",
            name="date_created",
            field=models.DateTimeField(default=bitapi.utils.now),
        ),
        migrations.AddField(
            model_name="subscriberequest",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
