# Generated by Django 4.2.9 on 2025-06-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0052_remove_subscriberequest_generate_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registration_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
