# Generated by Django 4.2.9 on 2025-07-01 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0053_alter_user_registration_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deep_scan_mode",
        ),
        migrations.RemoveField(
            model_name="user",
            name="free_plagiarism_attempts",
        ),
        migrations.RemoveField(
            model_name="user",
            name="used_words_deep_scan",
        ),
    ]
