# Generated by Django 4.2.9 on 2025-10-02 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0054_remove_user_deep_scan_mode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOptions",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="options",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("feedback", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
