# Generated by Django 4.2.9 on 2025-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0056_alter_subscriberequest_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroptions",
            name="overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
