# Generated by Django 4.2.9 on 2025-11-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0058_remove_user_used_british_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroptions",
            name="policy_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            """
            UPDATE users_useroptions AS options
            SET policy_accepted = u.policy_accepted
            FROM users_user AS u
            WHERE options.user_id = u.id;
            """
        ),
        migrations.RemoveField(
            model_name="user",
            name="policy_accepted",
        ),
        migrations.AddField(
            model_name="useroptions",
            name="policy_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useroptions",
            name="policy_ip",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="useroptions",
            name="policy_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
