customer_subscription_created = {
    "api_version": "2025-10-29.clover",
    "created": 1763557116,
    "data": {
        "object": {
            "application": "null",
            "application_fee_percent": "null",
            "automatic_tax": {
                "disabled_reason": "null",
                "enabled": False,
                "liability": "null",
            },
            "billing_cycle_anchor": 1763557112,
            "billing_cycle_anchor_config": "null",
            "billing_mode": {
                "flexible": {"proration_discounts": "included"},
                "type": "flexible",
                "updated_at": 1763557095,
            },
            "billing_thresholds": "null",
            "cancel_at": "null",
            "cancel_at_period_end": False,
            "canceled_at": "null",
            "cancellation_details": {
                "comment": "null",
                "feedback": "null",
                "reason": "null",
            },
            "collection_method": "charge_automatically",
            "created": 1763557112,
            "currency": "usd",
            "customer": "cus_TRgdbk7xcFh4Dw",
            "days_until_due": "null",
            "default_payment_method": "pm_1SVAxwLlv1dDDiBEz60D1vCA",
            "default_source": "null",
            "default_tax_rates": [],
            "description": "null",
            "discounts": [],
            "ended_at": "null",
            "id": "sub_1SVAxzLlv1dDDiBERp446EVf",
            "invoice_settings": {"account_tax_ids": "null", "issuer": {"type": "self"}},
            "items": {
                "data": [
                    {
                        "billing_thresholds": "null",
                        "created": 1763557113,
                        "current_period_end": 1766149112,
                        "current_period_start": 1763557112,
                        "discounts": [],
                        "id": "si_TS58SeDCovR36I",
                        "metadata": {},
                        "object": "subscription_item",
                        "plan": {
                            "active": True,
                            "amount": 10000,
                            "amount_decimal": "10000",
                            "billing_scheme": "per_unit",
                            "created": 1763466755,
                            "currency": "usd",
                            "id": "price_1SUnSZLlv1dDDiBEv6FvUgaX",
                            "interval": "month",
                            "interval_count": 1,
                            "livemode": False,
                            "metadata": {},
                            "meter": "null",
                            "nickname": "null",
                            "object": "plan",
                            "product": "prod_TRgqxO6WGSb4rz",
                            "tiers_mode": "null",
                            "transform_usage": "null",
                            "trial_period_days": "null",
                            "usage_type": "licensed",
                        },
                        "price": {
                            "active": True,
                            "billing_scheme": "per_unit",
                            "created": 1763466755,
                            "currency": "usd",
                            "custom_unit_amount": "null",
                            "id": "price_1SUnSZLlv1dDDiBEv6FvUgaX",
                            "livemode": False,
                            "lookup_key": "pro_month_subscription",
                            "metadata": {},
                            "nickname": "null",
                            "object": "price",
                            "product": "prod_TRgqxO6WGSb4rz",
                            "recurring": {
                                "interval": "month",
                                "interval_count": 1,
                                "meter": "null",
                                "trial_period_days": "null",
                                "usage_type": "licensed",
                            },
                            "tax_behavior": "unspecified",
                            "tiers_mode": "null",
                            "transform_quantity": "null",
                            "type": "recurring",
                            "unit_amount": 10000,
                            "unit_amount_decimal": "10000",
                        },
                        "quantity": 1,
                        "subscription": "sub_1SVAxzLlv1dDDiBERp446EVf",
                        "tax_rates": [],
                    }
                ],
                "has_more": False,
                "object": "list",
                "total_count": 1,
                "url": "/v1/subscription_items?subscription=sub_1SVAxzLlv1dDDiBERp446EVf",
            },
            "latest_invoice": "in_1SVAxxLlv1dDDiBEHwMReQBy",
            "livemode": False,
            "metadata": {},
            "next_pending_invoice_item_invoice": "null",
            "object": "subscription",
            "on_behalf_of": "null",
            "pause_collection": "null",
            "payment_settings": {
                "payment_method_options": {
                    "acss_debit": "null",
                    "bancontact": "null",
                    "card": {"network": "null", "request_three_d_secure": "automatic"},
                    "customer_balance": "null",
                    "konbini": "null",
                    "sepa_debit": "null",
                    "us_bank_account": "null",
                },
                "payment_method_types": "null",
                "save_default_payment_method": "off",
            },
            "pending_invoice_item_interval": "null",
            "pending_setup_intent": "null",
            "pending_update": "null",
            "plan": {
                "active": True,
                "amount": 10000,
                "amount_decimal": "10000",
                "billing_scheme": "per_unit",
                "created": 1763466755,
                "currency": "usd",
                "id": "price_1SUnSZLlv1dDDiBEv6FvUgaX",
                "interval": "month",
                "interval_count": 1,
                "livemode": False,
                "metadata": {},
                "meter": "null",
                "nickname": "null",
                "object": "plan",
                "product": "prod_TRgqxO6WGSb4rz",
                "tiers_mode": "null",
                "transform_usage": "null",
                "trial_period_days": "null",
                "usage_type": "licensed",
            },
            "presentment_details": {"presentment_currency": "eur"},
            "quantity": 1,
            "schedule": "null",
            "start_date": 1763557112,
            "status": "active",
            "test_clock": "null",
            "transfer_data": "null",
            "trial_end": "null",
            "trial_settings": {
                "end_behavior": {"missing_payment_method": "create_invoice"}
            },
            "trial_start": "null",
        }
    },
    "id": "evt_1SVAy0Llv1dDDiBEAT8wepCy",
    "livemode": False,
    "object": "event",
    "pending_webhooks": 3,
    "request": {
        "id": "null",
        "idempotency_key": "5ba355d4-2fbe-4e31-8285-512f2d1ba6cb",
    },
    "type": "customer.subscription.created",
}
payment_intent_payment_failed = {
    "amount": 10000,
    "amount_capturable": 0,
    "amount_details": {"tip": {}},
    "amount_received": 0,
    "application": None,
    "application_fee_amount": None,
    "automatic_payment_methods": None,
    "canceled_at": None,
    "cancellation_reason": None,
    "capture_method": "automatic",
    "client_secret": "pi_3SVaCSLlv1dDDiBE1LK5MQRT_secret_Y6B2d7XGrik0Yh8hQgSskvXzx",
    "confirmation_method": "automatic",
    "created": 1763654112,
    "currency": "usd",
    "customer": "cus_TRgdbk7xcFh4Dw",
    "description": "Subscription creation",
    "excluded_payment_method_types": None,
    "id": "pi_3SVaCSLlv1dDDiBE1LK5MQRT",
    "last_payment_error": {
        "advice_code": "try_again_later",
        "charge": "ch_3SVaCSLlv1dDDiBE1RJkdH7S",
        "code": "card_declined",
        "decline_code": "generic_decline",
        "doc_url": "https://stripe.com/docs/error-codes/card-declined",
        "message": "Your card was declined.",
        "network_decline_code": "01",
        "payment_method": {
            "allow_redisplay": "limited",
            "billing_details": {
                "address": {
                    "city": None,
                    "country": "NL",
                    "line1": None,
                    "line2": None,
                    "postal_code": None,
                    "state": None,
                },
                "email": "jennrosen@example.com",
                "name": "\u0432\u044b\u0444\u043b",
                "phone": None,
                "tax_id": None,
            },
            "card": {
                "brand": "visa",
                "checks": {
                    "address_line1_check": None,
                    "address_postal_code_check": None,
                    "cvc_check": "pass",
                },
                "country": "US",
                "display_brand": "visa",
                "exp_month": 11,
                "exp_year": 2030,
                "fingerprint": "UuiYtYNKN1Ob4iVS",
                "funding": "credit",
                "generated_from": None,
                "last4": "0341",
                "networks": {"available": ["visa"], "preferred": None},
                "regulated_status": "unregulated",
                "three_d_secure_usage": {"supported": True},
                "wallet": None,
            },
            "created": 1763670899,
            "customer": None,
            "id": "pm_1SVeZDLlv1dDDiBEDDkpi4rU",
            "livemode": False,
            "metadata": {},
            "object": "payment_method",
            "type": "card",
        },
        "type": "card_error",
    },
    "latest_charge": "ch_3SVaCSLlv1dDDiBE1RJkdH7S",
    "livemode": False,
    "metadata": {},
    "next_action": None,
    "object": "payment_intent",
    "on_behalf_of": None,
    "payment_details": {
        "customer_reference": None,
        "order_reference": "cs_test_b1Hy7dSfvkEfCIZ7P",
    },
    "payment_method": None,
    "payment_method_configuration_details": None,
    "payment_method_options": {
        "card": {
            "installments": None,
            "mandate_options": None,
            "network": None,
            "request_three_d_secure": "automatic",
            "setup_future_usage": "off_session",
        }
    },
    "payment_method_types": ["card"],
    "processing": None,
    "receipt_email": None,
    "review": None,
    "setup_future_usage": "off_session",
    "shipping": None,
    "source": None,
    "statement_descriptor": None,
    "statement_descriptor_suffix": None,
    "status": "requires_payment_method",
    "transfer_data": None,
    "transfer_group": None,
}
invoice_payment_succeeded = {
    "account_country": "US",
    "account_name": None,
    "account_tax_ids": None,
    "amount_due": 1000,
    "amount_overpaid": 0,
    "amount_paid": 1000,
    "amount_remaining": 0,
    "amount_shipping": 0,
    "application": None,
    "attempt_count": 1,
    "attempted": True,
    "auto_advance": False,
    "automatic_tax": {
        "disabled_reason": None,
        "enabled": False,
        "liability": None,
        "provider": None,
        "status": None,
    },
    "automatically_finalizes_at": None,
    "billing_reason": "subscription_cycle",
    "collection_method": "charge_automatically",
    "created": 1763586425,
    "currency": "usd",
    "custom_fields": None,
    "customer": "cus_TRgdbk7xcFh4Dw",
    "customer_address": None,
    "customer_email": "jennrosen@example.com",
    "customer_name": "1",
    "customer_phone": None,
    "customer_shipping": None,
    "customer_tax_exempt": "none",
    "customer_tax_ids": [],
    "default_payment_method": None,
    "default_source": None,
    "default_tax_rates": [],
    "description": None,
    "discounts": [],
    "due_date": None,
    "effective_at": 1763593623,
    "ending_balance": 0,
    "footer": None,
    "from_invoice": None,
    "hosted_invoice_url": "https://invoice.stripe.com/i/acct_1STPJlLlv1dDDiBE/test_YWNjdF8xU1RQSmxMbHYxZEREaUJFLF9UU0QwaEpRY290MXYyTlR0UmFHcnhhUzBVbkJOd1JyLDE1NDEzNDQyOQ0200I77BfRLQ?s=ap",
    "id": "in_1SVIajLlv1dDDiBER1F7BUew",
    "invoice_pdf": "https://pay.stripe.com/invoice/acct_1STPJlLlv1dDDiBE/test_YWNjdF8xU1RQSmxMbHYxZEREaUJFLF9UU0QwaEpRY290MXYyTlR0UmFHcnhhUzBVbkJOd1JyLDE1NDEzNDQyOQ0200I77BfRLQ/pdf?s=ap",
    "issuer": {"type": "self"},
    "last_finalization_error": None,
    "latest_revision": None,
    "lines": {
        "data": [
            {
                "amount": 1000,
                "currency": "usd",
                "description": "1 \u00d7 pro_day_subscription (at $10.00 / day)",
                "discount_amounts": [],
                "discountable": True,
                "discounts": [],
                "id": "il_1SVIadLlv1dDDiBEHumUNhoL",
                "invoice": "in_1SVIajLlv1dDDiBER1F7BUew",
                "livemode": False,
                "metadata": {},
                "object": "line_item",
                "parent": {
                    "invoice_item_details": None,
                    "subscription_item_details": {
                        "invoice_item": None,
                        "proration": False,
                        "proration_details": {"credited_items": None},
                        "subscription": "sub_1SUw78Llv1dDDiBE0WEuRrU6",
                        "subscription_item": "si_TRpm0YFc267Ni0",
                    },
                    "type": "subscription_item_details",
                },
                "period": {"end": 1763672819, "start": 1763586419},
                "pretax_credit_amounts": [],
                "pricing": {
                    "price_details": {
                        "price": "price_1SUuh9Llv1dDDiBEtp96yrJG",
                        "product": "prod_TRoJdjVb9GWYQQ",
                    },
                    "type": "price_details",
                    "unit_amount_decimal": "1000",
                },
                "quantity": 1,
                "taxes": [],
            }
        ],
        "has_more": False,
        "object": "list",
        "total_count": 1,
        "url": "/v1/invoices/in_1SVIajLlv1dDDiBER1F7BUew/lines",
    },
    "livemode": False,
    "metadata": {},
    "next_payment_attempt": None,
    "number": "BU5YKKJR-0023",
    "object": "invoice",
    "on_behalf_of": None,
    "parent": {
        "quote_details": None,
        "subscription_details": {
            "metadata": {},
            "subscription": "sub_1SUw78Llv1dDDiBE0WEuRrU6",
        },
        "type": "subscription_details",
    },
    "payment_settings": {
        "default_mandate": None,
        "payment_method_options": {
            "acss_debit": None,
            "bancontact": None,
            "card": {"request_three_d_secure": "automatic"},
            "customer_balance": None,
            "konbini": None,
            "sepa_debit": None,
            "us_bank_account": None,
        },
        "payment_method_types": None,
    },
    "period_end": 1763586419,
    "period_start": 1763500019,
    "post_payment_credit_notes_amount": 0,
    "pre_payment_credit_notes_amount": 0,
    "receipt_number": None,
    "rendering": None,
    "shipping_cost": None,
    "shipping_details": None,
    "starting_balance": 0,
    "statement_descriptor": None,
    "status": "paid",
    "status_transitions": {
        "finalized_at": 1763593623,
        "marked_uncollectible_at": None,
        "paid_at": 1763593623,
        "voided_at": None,
    },
    "subtotal": 1000,
    "subtotal_excluding_tax": 1000,
    "test_clock": None,
    "total": 1000,
    "total_discount_amounts": [],
    "total_excluding_tax": 1000,
    "total_pretax_credit_amounts": [],
    "total_taxes": [],
    "webhooks_delivered_at": 1763590017,
}
charge_failed = {
    "amount": 10000,
    "amount_captured": 0,
    "amount_refunded": 0,
    "application": None,
    "application_fee": None,
    "application_fee_amount": None,
    "balance_transaction": None,
    "billing_details": {
        "address": {
            "city": None,
            "country": "NL",
            "line1": None,
            "line2": None,
            "postal_code": None,
            "state": None,
        },
        "email": "jennrosen@example.com",
        "name": "\u0432\u044b\u0444\u043b",
        "phone": None,
        "tax_id": None,
    },
    "calculated_statement_descriptor": "Stripe",
    "captured": False,
    "created": 1763670900,
    "currency": "usd",
    "customer": "cus_TRgdbk7xcFh4Dw",
    "description": "Subscription creation",
    "destination": None,
    "dispute": None,
    "disputed": False,
    "failure_balance_transaction": None,
    "failure_code": "card_declined",
    "failure_message": "Your card was declined.",
    "fraud_details": {},
    "id": "ch_3SVaCSLlv1dDDiBE1RJkdH7S",
    "livemode": False,
    "metadata": {},
    "object": "charge",
    "on_behalf_of": None,
    "order": None,
    "outcome": {
        "advice_code": "try_again_later",
        "network_advice_code": None,
        "network_decline_code": "01",
        "network_status": "declined_by_network",
        "reason": "generic_decline",
        "risk_level": "normal",
        "risk_score": 19,
        "seller_message": "The bank did not return any further details with this decline.",
        "type": "issuer_declined",
    },
    "paid": False,
    "payment_intent": "pi_3SVaCSLlv1dDDiBE1LK5MQRT",
    "payment_method": "pm_1SVeZDLlv1dDDiBEDDkpi4rU",
    "payment_method_details": {
        "card": {
            "amount_authorized": None,
            "authorization_code": "589169",
            "brand": "visa",
            "checks": {
                "address_line1_check": None,
                "address_postal_code_check": None,
                "cvc_check": "pass",
            },
            "country": "US",
            "exp_month": 11,
            "exp_year": 2030,
            "extended_authorization": {"status": "disabled"},
            "fingerprint": "UuiYtYNKN1Ob4iVS",
            "funding": "credit",
            "incremental_authorization": {"status": "unavailable"},
            "installments": None,
            "last4": "0341",
            "mandate": None,
            "multicapture": {"status": "unavailable"},
            "network": "visa",
            "network_token": {"used": False},
            "network_transaction_id": "851171058911689",
            "overcapture": {
                "maximum_amount_capturable": 10000,
                "status": "unavailable",
            },
            "regulated_status": "unregulated",
            "three_d_secure": None,
            "wallet": None,
        },
        "type": "card",
    },
    "presentment_details": {"presentment_amount": 9016, "presentment_currency": "eur"},
    "radar_options": {},
    "receipt_email": None,
    "receipt_number": None,
    "receipt_url": None,
    "refunded": False,
    "review": None,
    "shipping": None,
    "source": None,
    "source_transfer": None,
    "statement_descriptor": None,
    "statement_descriptor_suffix": None,
    "status": "failed",
    "transfer_data": None,
    "transfer_group": None,
}
