# Generated by Django 5.2.6 on 2025-09-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_file',
        ),
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='text_string',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
