# Generated by Django 5.2.6 on 2025-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderator', '0002_rename_image_image_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='text',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='video',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=None),
        ),
    ]
