# Generated by Django 5.2.6 on 2025-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_moderator', '0005_alter_image_percentage_of_illegality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='text',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='percentage_of_illegality',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
