# Generated by Django 5.2.8 on 2025-11-21 16:09

import django.db.models.deletion
import subscription_payments.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=256)),
                ("status", models.CharField(choices=[], default="init")),
                ("amount", models.FloatField(null=True)),
                (
                    "date_created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("status", models.CharField(choices=[], default="active")),
                ("month_price", models.FloatField(default=0)),
                (
                    "start_period",
                    models.DateTimeField(default=subscription_payments.helpers.now),
                ),
                ("delay", models.DurationField(default=None, null=True)),
                ("plan", models.CharField(default="free_plan", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
