# Generated by Django 5.2.8 on 2025-11-21 16:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, max_length=256, primary_key=True, serialize=False
            ),
        ),
    ]
