# Generated by Django 5.2.8 on 2025-11-18 21:07

import django.db.models.deletion
import subscription_payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                subscription_payments.models.SubscriptionStatus[
                                    "active"
                                ],
                                subscription_payments.models.SubscriptionStatus[
                                    "active"
                                ],
                            ),
                            (
                                subscription_payments.models.SubscriptionStatus[
                                    "user_canceled"
                                ],
                                subscription_payments.models.SubscriptionStatus[
                                    "user_canceled"
                                ],
                            ),
                            (
                                subscription_payments.models.SubscriptionStatus[
                                    "user_did_not_pay"
                                ],
                                subscription_payments.models.SubscriptionStatus[
                                    "user_did_not_pay"
                                ],
                            ),
                        ]
                    ),
                ),
                ("month_price", models.FloatField()),
                ("start_period", models.DateTimeField()),
                ("delay", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
