# Generated by Django 5.2.8 on 2025-11-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(max_length=256),
        ),
    ]
