# Generated by Django 5.2.8 on 2025-11-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
