# Generated by Django 5.2.8 on 2025-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0002_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(null=True),
        ),
    ]
