# Generated by Django 5.2.8 on 2025-11-21 15:44

import subscription_payments.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription_payments", "0003_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="delay",
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="month_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(default="free_plan", max_length=64),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_period",
            field=models.DateTimeField(default=subscription_payments.helpers.now),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(choices=[], default="active"),
        ),
    ]
